name: Unit Tests

on: 
  push:
    # only trigger on pushes to development
    branches: [ development ]
  # pull_request:
    # branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env: 
      PORT: ${{ secrets.PORT }}
      COOKIE_PARSER_SECRET_CODE: ${{ secrets.COOKIE_PARSER_SECRET_CODE }}
      DEV_MONGO: ${{ secrets.DEV_MONGO }}
      FRONT_END_ORIGIN_URL: ${{ secrets.FRONT_END_ORIGIN_URL }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    strategy:
      matrix:
        node-version: [18.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: tests
        run: npm run test:coverage

  merge-if-tests-pass:
    needs: run-tests # Wait for the "run-tests" job to pass before running this job
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - uses: everlytic/branch-merge@1.1.2
         with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'